#!/usr/bin/env node

/**
 * Dynamic Hook - Executed by Rapala Router
 * Generated by Rapala Hook Generator
 * Description: listen put this hook and modify and turn it into a rapala hook - creates a simple test hook that logs execution to verify Claude Code is calling hooks
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

class DynamicGeneratedHook {
  constructor() {
    this.name = 'listen-put-this-hook-and-modif-742866';
    this.description = 'listen put this hook and modify and turn it into a rapala hook - creates a simple test hook that logs execution to verify Claude Code is calling hooks';
  }

  async execute(input) {
    try {
      console.error(`🎣 Executing: ${this.name}`);
      
      // Simple test hook that logs execution to verify Claude Code is calling hooks
      const logFile = path.join(process.cwd(), 'rapala-hook-test.log');
      const timestamp = new Date().toISOString();
      const toolName = input.tool_name || 'Unknown';
      const filePath = input.tool_input?.file_path || 'no file';
      
      const logEntry = `${timestamp} - Rapala hook executed! Tool: ${toolName}, File: ${filePath}\n`;
      
      // Log that this hook was called
      fs.appendFileSync(logFile, logEntry);
      
      console.error(`📝 Logged execution to: ${logFile}`);
      console.error(`🔧 Tool: ${toolName}, File: ${filePath}`);
      
      return { success: true, message: 'Simple test hook executed successfully' };
    } catch (error) {
      console.error(`❌ Hook ${this.name} failed:`, error.message);
      return { success: false, error: error.message };
    }
  }
}

// Main execution when called by Rapala Router
async function main() {
  try {
    // Read input from stdin (sent by Rapala Router)
    let inputData = '';
    
    if (process.env.HOOK_INPUT) {
      inputData = process.env.HOOK_INPUT;
    } else {
      // Read from stdin
      for await (const chunk of process.stdin) {
        inputData += chunk;
      }
    }
    
    const input = JSON.parse(inputData);
    const hook = new DynamicGeneratedHook();
    const result = await hook.execute(input);
    
    process.exit(result.success ? 0 : 1);
  } catch (error) {
    console.error('Hook execution failed:', error.message);
    process.exit(1);
  }
}

// Run if called directly
if (require.main === module) {
  main();
}

module.exports = DynamicGeneratedHook;