#!/usr/bin/env node

/**
 * Dynamic Hook - Executed by Rapala Router
 * Generated by Rapala Hook Generator
 * Description: make it so every command gets ran inside of a tmux session every bash command unique to each session in 1 tmux session
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

class DynamicGeneratedHook {
  constructor() {
    this.name = 'make-it-so-every-command-gets-439288';
    this.description = 'make it so every command gets ran inside of a tmux session every bash command unique to each session in 1 tmux session';
  }

  async execute(input) {
    try {
      console.error(`🎣 Executing: ${this.name}`);
      
      // Dynamic hook logic - executed by Rapala Router
      
      // Tmux session management for bash commands
      const { execSync } = require('child_process');
      
      if (input.tool_name === 'Bash') {
        const command = input.tool_input?.command || '';
        const sessionName = 'claude-bash-' + Date.now();
        
        console.error('🎣 Creating dedicated tmux session for bash command');
        console.error('Session:', sessionName);
        console.error('Command:', command);
        
        try {
          // Create tmux session and execute command in new pane
          execSync(`tmux new-session -d -s "${sessionName}" bash -c "
            echo 'Claude Code Bash Command Session'
            echo 'Session: ${sessionName}'
            echo 'Command: ${command}'
            echo '======================================'
            ${command}
            echo '======================================'
            echo 'Command completed. This session will close in 10 minutes...'
            sleep 600
            tmux kill-session -t ${sessionName}
          "`, { stdio: 'inherit' });
          
          console.error('✅ Command executed in tmux session:', sessionName);
          console.error('💡 Use "tmux attach -t', sessionName, '" to view the session');
          console.error('⏰ Session will auto-close in 10 minutes');
          
        } catch (error) {
          console.error('❌ Failed to create tmux session:', error.message);
        }
      }
      
      return { success: true };
    } catch (error) {
      console.error(`❌ Hook ${this.name} failed:`, error.message);
      return { success: false, error: error.message };
    }
  }
}

// Main execution when called by Rapala Router
async function main() {
  try {
    // Read input from stdin (sent by Rapala Router)
    let inputData = '';
    
    if (process.env.HOOK_INPUT) {
      inputData = process.env.HOOK_INPUT;
    } else {
      // Read from stdin
      for await (const chunk of process.stdin) {
        inputData += chunk;
      }
    }
    
    const input = JSON.parse(inputData);
    const hook = new DynamicGeneratedHook();
    const result = await hook.execute(input);
    
    process.exit(result.success ? 0 : 1);
  } catch (error) {
    console.error('Hook execution failed:', error.message);
    process.exit(1);
  }
}

// Run if called directly
if (require.main === module) {
  main();
}

module.exports = DynamicGeneratedHook;