#!/usr/bin/env node

/**
 * Dynamic Hook - Executed by Rapala Router
 * Generated by Rapala Hook Generator
 * Description: Format Python files after editing
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

class DynamicGeneratedHook {
  constructor() {
    this.name = 'format-python-files-after-edit-212827';
    this.description = 'Format Python files after editing';
  }

  async execute(input) {
    try {
      console.error(`🎣 Executing: ${this.name}`);
      
      // Dynamic hook logic - executed by Rapala Router
      
      // Generated hook logic for: Format Python files after editing
      const { execSync } = require('child_process');
      
      console.error('🎣 Executing generated hook:', 'Format Python files after editing');
      
      try {
        const command = 'black . --quiet 2>/dev/null || true';
        execSync(command, { stdio: 'inherit' });
      } catch (error) {
        console.error('Hook execution failed:', error.message);
      }
      
      return { success: true };
    } catch (error) {
      console.error(`❌ Hook ${this.name} failed:`, error.message);
      return { success: false, error: error.message };
    }
  }
}

// Main execution when called by Rapala Router
async function main() {
  try {
    // Read input from stdin (sent by Rapala Router)
    let inputData = '';
    
    if (process.env.HOOK_INPUT) {
      inputData = process.env.HOOK_INPUT;
    } else {
      // Read from stdin
      for await (const chunk of process.stdin) {
        inputData += chunk;
      }
    }
    
    const input = JSON.parse(inputData);
    const hook = new DynamicGeneratedHook();
    const result = await hook.execute(input);
    
    process.exit(result.success ? 0 : 1);
  } catch (error) {
    console.error('Hook execution failed:', error.message);
    process.exit(1);
  }
}

// Run if called directly
if (require.main === module) {
  main();
}

module.exports = DynamicGeneratedHook;